baseURL: "https://k8s-book.vupti.me"
languageCode: "en-us"
title: "My Kubernetes Book"

#theme: "book"
theme: "learn"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1


blackfriday:
  extensions:
    - hardLineBreak

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo: true

# Enable Google Analytics
# googleAnalytics: UA-5631150-8

# Enable global emoji support
enableEmoji: true

pygmentsCodeFences: true
pygmentsStyle: "monokai"


outputs:
  home: ["HTML","RSS", "JSON"]

menu:
  shortcuts:
  - name: "<i class='fab fa-fw fa-github'></i> GitHub repo"
    url: "https://github.com/lrivallain/git-book-kubernetes"
    weight: 10
  - name: "<i class='fas fa-fw fa-user'></i> About"
    url: "https://ludovic.rivallain.fr"
    weight: 20
  - name: "<i class='fas fa-fw fa-globe-europe'></i> vUptime.io"
    url: "https://vuptime.io"
    weight: 30

# Site parameters
params:
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL: "https://github.com/lrivallain/git-book-kubernetes/tree/master/content/"
  # Author of the site, will be used in meta information
  author: "Ludovic Rivallain"
  # Description of the site, will be used in meta information
  description: "A personal note-book to keep some relevant informations about Kubernetes and k8s related products, for my personal and/or professional use."
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks: true
  # Disable search function. It will hide search bar
  disableSearch: false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting: false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard: true
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle: false
  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton: false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton: true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb: false
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid: true
  # Specifies the remote location of the mermaid js
  customMermaidURL: "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev: false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby: "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant: ""
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css: ["css/style.css"]
  # Change the title separator. Default to "::".
  titleSeparator: "–"